Variation tracks for Human CHM13
Ensembl/ensembl-rapid pull request #20
Opened 2023-02-16 12:57 UTC by Gurpreet-Ghattaoraya

Adding variation tracks for human T2T-CHM13.

Example of working tracks are available on this sandbox link: http://wp-np2-25.ebi.ac.uk:8001/Homo_sapiens_GCA_009914755.4/Location/View?db=core;r=1:375270-375521;v=rs78067484;vdb=variation;vf=7:56179501:A_G:gnomADg

2023-02-16 16:38 UTC, jamie-m-a requested changes
Needs updating with the more complete GWAS id and updated descriptions for both gwas and dbsnp tracks

2023-02-16 17:05 UTC, jamie-m-a approved these changes
Looks good!

2023-02-16 17:09 UTC, jyothishnt commented on conf/json/homo_sapiens_gca009914755v4_vcf.json
> +      "filename_template" : "/nfs/services/nobackup/ensweb/variation-pgs/CHM13/Homo_sapiens-GCA_009914755.4-2023_01-GWAS.vcf.gz"
Same here

2023-02-17 17:41 UTC, Gurpreet-Ghattaoraya commented on conf/json/homo_sapiens_gca009914755v4_vcf.json
> +      "filename_template" : "/nfs/services/nobackup/ensweb/variation-pgs/CHM13/Homo_sapiens-GCA_009914755.4-2023_01-dbSNP155.vcf.gz"
Changed to point to the FTP path instead.

2023-02-17 18:02 UTC, jamie-m-a reviewed
I'm slightly confused because the clinvar and gnomad files are shwoing as an /nfs location and the 2 new tracks as an https link?

Shouldn't these be consistent? @jyothishnt can you comment?

It might be that we need to wait for info from Likhitha on monday as I think she had this set up with Anne as to where the files should go.

2023-02-20 15:06 UTC, jamie-m-a reviewed
Looks correct @jyothishnt I can't view files in that dir - can you confirm they are present - thanks!

2023-02-20 15:50 UTC, Gurpreet-Ghattaoraya commented
Closing this PR and reopening as fresh. This PR has become messy.

2023-02-20 15:50 UTC, closed without merging